Rabbitmq settings json
NCAR/music-box-interactive pull request #298
Opened 2022-08-08 23:16 UTC by jwoody02

- created settings json
- implemented settings in all classes where applicable
- #297

2022-08-08 23:17 UTC, pep8speaks commented
Hello @jwoody02! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`interactive/dashboard/api.py`](https://github.com/NCAR/music-box-interactive/blob/08e8045b936d94725b5cf60d024b507fe2832f41/interactive/dashboard/api.py):

> [Line 45:80](https://github.com/NCAR/music-box-interactive/blob/08e8045b936d94725b5cf60d024b507fe2832f41/interactive/dashboard/api.py#L45): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (112 > 79 characters)
> [Line 46:80](https://github.com/NCAR/music-box-interactive/blob/08e8045b936d94725b5cf60d024b507fe2832f41/interactive/dashboard/api.py#L46): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 47:80](https://github.com/NCAR/music-box-interactive/blob/08e8045b936d94725b5cf60d024b507fe2832f41/interactive/dashboard/api.py#L47): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (125 > 79 characters)
> [Line 49:1](https://github.com/NCAR/music-box-interactive/blob/08e8045b936d94725b5cf60d024b507fe2832f41/interactive/dashboard/api.py#L49): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 70:80](https://github.com/NCAR/music-box-interactive/blob/08e8045b936d94725b5cf60d024b507fe2832f41/interactive/dashboard/api.py#L70): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 71:80](https://github.com/NCAR/music-box-interactive/blob/08e8045b936d94725b5cf60d024b507fe2832f41/interactive/dashboard/api.py#L71): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 99:80](https://github.com/NCAR/music-box-interactive/blob/08e8045b936d94725b5cf60d024b507fe2832f41/interactive/dashboard/api.py#L99): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 164:21](https://github.com/NCAR/music-box-interactive/blob/08e8045b936d94725b5cf60d024b507fe2832f41/interactive/dashboard/api.py#L164): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 241:15](https://github.com/NCAR/music-box-interactive/blob/08e8045b936d94725b5cf60d024b507fe2832f41/interactive/dashboard/api.py#L241): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 263:13](https://github.com/NCAR/music-box-interactive/blob/08e8045b936d94725b5cf60d024b507fe2832f41/interactive/dashboard/api.py#L263): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 346:80](https://github.com/NCAR/music-box-interactive/blob/08e8045b936d94725b5cf60d024b507fe2832f41/interactive/dashboard/api.py#L346): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 364:80](https://github.com/NCAR/music-box-interactive/blob/08e8045b936d94725b5cf60d024b507fe2832f41/interactive/dashboard/api.py#L364): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 365:35](https://github.com/NCAR/music-box-interactive/blob/08e8045b936d94725b5cf60d024b507fe2832f41/interactive/dashboard/api.py#L365): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 387:80](https://github.com/NCAR/music-box-interactive/blob/08e8045b936d94725b5cf60d024b507fe2832f41/interactive/dashboard/api.py#L387): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 392:15](https://github.com/NCAR/music-box-interactive/blob/08e8045b936d94725b5cf60d024b507fe2832f41/interactive/dashboard/api.py#L392): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 414:15](https://github.com/NCAR/music-box-interactive/blob/08e8045b936d94725b5cf60d024b507fe2832f41/interactive/dashboard/api.py#L414): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 433:80](https://github.com/NCAR/music-box-interactive/blob/08e8045b936d94725b5cf60d024b507fe2832f41/interactive/dashboard/api.py#L433): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 438:15](https://github.com/NCAR/music-box-interactive/blob/08e8045b936d94725b5cf60d024b507fe2832f41/interactive/dashboard/api.py#L438): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 454:80](https://github.com/NCAR/music-box-interactive/blob/08e8045b936d94725b5cf60d024b507fe2832f41/interactive/dashboard/api.py#L454): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 458:15](https://github.com/NCAR/music-box-interactive/blob/08e8045b936d94725b5cf60d024b507fe2832f41/interactive/dashboard/api.py#L458): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 459:80](https://github.com/NCAR/music-box-interactive/blob/08e8045b936d94725b5cf60d024b507fe2832f41/interactive/dashboard/api.py#L459): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 480:15](https://github.com/NCAR/music-box-interactive/blob/08e8045b936d94725b5cf60d024b507fe2832f41/interactive/dashboard/api.py#L480): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 498:80](https://github.com/NCAR/music-box-interactive/blob/08e8045b936d94725b5cf60d024b507fe2832f41/interactive/dashboard/api.py#L498): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 535:80](https://github.com/NCAR/music-box-interactive/blob/08e8045b936d94725b5cf60d024b507fe2832f41/interactive/dashboard/api.py#L535): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 540:15](https://github.com/NCAR/music-box-interactive/blob/08e8045b936d94725b5cf60d024b507fe2832f41/interactive/dashboard/api.py#L540): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 556:80](https://github.com/NCAR/music-box-interactive/blob/08e8045b936d94725b5cf60d024b507fe2832f41/interactive/dashboard/api.py#L556): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 595:80](https://github.com/NCAR/music-box-interactive/blob/08e8045b936d94725b5cf60d024b507fe2832f41/interactive/dashboard/api.py#L595): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 638:80](https://github.com/NCAR/music-box-interactive/blob/08e8045b936d94725b5cf60d024b507fe2832f41/interactive/dashboard/api.py#L638): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 643:15](https://github.com/NCAR/music-box-interactive/blob/08e8045b936d94725b5cf60d024b507fe2832f41/interactive/dashboard/api.py#L643): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 746:80](https://github.com/NCAR/music-box-interactive/blob/08e8045b936d94725b5cf60d024b507fe2832f41/interactive/dashboard/api.py#L746): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (109 > 79 characters)
> [Line 749:80](https://github.com/NCAR/music-box-interactive/blob/08e8045b936d94725b5cf60d024b507fe2832f41/interactive/dashboard/api.py#L749): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (92 > 79 characters)
> [Line 753:1](https://github.com/NCAR/music-box-interactive/blob/08e8045b936d94725b5cf60d024b507fe2832f41/interactive/dashboard/api.py#L753): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 757:45](https://github.com/NCAR/music-box-interactive/blob/08e8045b936d94725b5cf60d024b507fe2832f41/interactive/dashboard/api.py#L757): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 757:80](https://github.com/NCAR/music-box-interactive/blob/08e8045b936d94725b5cf60d024b507fe2832f41/ [...]

2022-08-09 14:42 UTC, K20shores requested changes

2022-08-09 14:42 UTC, K20shores commented on interactive/update_environment_variables.py
> +        os.environ["rabbit-mq-host"] = settings["rabbit-mq-host"]
The lines assigning into `os.environ` can be replaced with `os.environ.update(settings)`?

2022-08-12 20:27 UTC, jwoody02 commented
closing PR and moving to new one

2022-08-12 20:27 UTC, closed without merging